#!/bin/bash
mkdir data
mkdir Bin

echo UUUUUUUUUiUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUuUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU|minimodem --tx --ascii --alsa -f ./data/nnapped.bin 100

gcc ./src/Map.c -o ./Bin/mAp -lm

xxd ./data/nnapped.bin |head

./Bin/mAp

xxd ./data/nnapped.bin |head -n30

